### PR TITLE
Fix profile loading when passed an explicit profile

### LINKED ISSUE #111: Profile loading is reading the credentials file instead of the config file
I've noticed that this extension is ignoring `source_profile` as defined in `~/.aws/config`. 

Based on some cursory searches, it seems that this is because `GetProfile` is trying to read the profiles out of the credentials file (~/.aws/credentials) instead of the config file: https://github.com/duckdb/duckdb-aws/blob/f855eb3dce37700bfd36fe906a683e4be17dcaf6/src/aws_secret.cpp#L60-L79 - by using `GetCredentialsProfileFilename` instead of [`GetConfigProfileFilename`](https://github.com/aws/aws-sdk-cpp/blob/9000aa261c6ade3cb53269bef48b0e8863caf8d4/src/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp#L114). Is there any known reason for this or should this just be changed to read out of the config file instead?

### PR DESCRIPTION
**Pull request by jtanx**
Profiles should be read out of the config file, not credentials file

I believe this fixes #111

### CODE REVIEW

File: src/aws_secret.cpp [hunk 1]
```diff
@@ -37,9 +37,9 @@ static string certFileLocations[] = {
 
 //! Parse and set the remaining options
 static void ParseCoreS3Config(CreateSecretInput &input, KeyValueSecret &secret) {
-	vector<string> options = {"key_id",    "secret",        "region",
-	                          "endpoint",  "session_token", "endpoint",
```
Comment (jtanx) [inline src/aws_secret.cpp:41]: endpoint was duplicated

**Comment by jtanx** [comment]
ah yep, done

File: src/aws_secret.cpp (hunk 1 above)
Comment (benfleis) [reply src/aws_secret.cpp:41]: great catch

**Comment by jtanx** [comment]
Are there instructions for running the minio tests locally?

**Comment by jtanx** [comment]
Alright I just ran the actions on my fork and the tests work now.

**Comment by jtanx** [comment]
@Tmonster any chance for another review?

**Comment by nrsmac** [comment]
@Tmonster +1!

File: src/aws_secret.cpp [hunk 2]
```diff
@@ -65,26 +65,25 @@ static unique_ptr<KeyValueSecret> ConstructBaseS3Secret(vector<string> &prefix_p
...
-	// get file path where aws credentials are stored.
-	// comes from AWS_SHARED_CREDENTIALS_FILE
-	auto credentials_file_path = Aws::Auth::ProfileConfigFileAWSCredentialsProvider::GetCredentialsProfileFilename();
+	// get file path where aws config is stored.
+	// comes from AWS_CONFIG_FILE
+	auto config_file_path = Aws::Auth::GetConfigProfileFilename();
 	// get the profile from within that file
 	Aws::Map<Aws::String, Aws::Config::Profile> profiles;
-	Aws::Config::AWSConfigFileProfileConfigLoader loader(credentials_file_path);
+	Aws::Config::AWSConfigFileProfileConfigLoader loader(config_file_path, true);
```
Comment (Tmonster) [inline src/aws_secret.cpp:73]: Maybe in the future we will want a setting for the `useProfilePrefix`, but don't think that is needed here

**Review by Tmonster — APPROVED** [review]
LGTM thanks!

**Comment by jtanx** [comment]
Nice, thanks for reviewing; do I also need someone else to review to be able to merge?

**Comment by Tmonster** [comment]
nope, thanks for the PR!
